/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import java.util.Arrays;

public class LinkedList {

  Node head=null;
LinkedList(){

}
  public LinkedList(String item) {
    head = new Node(item);
  }


  public static void main(String[] args) {
    LinkedList newList = new LinkedList("head");
    newList.insert("hello");
    newList.insert("husam");
    newList.insert("high");
    newList.insert("low");
    System.out.println(newList.tostring());
  }

  public void insert(String value) {
    Node newHead = new Node(value);

    Node current = head;
    while (current.next != null) {

        current = current.next;

    }
    current.next=newHead;

  }
  public boolean includes(String search) {
 Node current = head;
 try {


    while (current != null) {
      if (current.value == search) {
        return true;
      } else {
        current=current.next;
      }
    }
 }catch (Exception ex){
   System.out.println(ex);
 }
    return  false;
  }
public String tostring(){
    String allValues="";
  Node current = head;
 while (current!=null){
   allValues+="{"+current.value+"}"+"->";
   current=current.next;

 }
    allValues+="NULL";
 return allValues;
}
}

