/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linkedList;

import org.junit.Test;
import static org.junit.Assert.*;

public class LinkedListTest {
@Test public void testinsert(){
    LinkedList newList = new LinkedList("hi");
    newList.insert("hello");
    assertEquals("The result is hello", "hello", testinsert(newList));
}
}
