/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackandqueues;

public class App {

    public static void main(String[] args) {

 Queue test1=new Queue();
 test1.enqueue(1);
      test1.enqueue(2);
      test1.enqueue(3);
      System.out.println(test1.dequeue());
      System.out.println(test1.dequeue());
    }

}
