/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import java.util.ArrayList;
import java.util.List;

public class HashTable {

 public static void main(String[] args){
HashTable test=new HashTable();
HashNode node=new HashNode("sam","hadd",null);
   HashNode node1=new HashNode("mas","husamm",null);
test.add(node);
   test.add(node1);
   test.get("mas");
   System.out.println( test.get("sam"));
  }
  HashNode[] hashTable=new HashNode[100];

public void add(HashNode node){

Integer index=hash((String) node.key);
if(hashTable[index]!=null){
  while ((hashTable[index].next!=null)){
    hashTable[index]=hashTable[index].next;
  }
hashTable[index].next=node;
}
else {
  hashTable[index]=node;
}
}
public Integer  hash(String key){
    Integer hash=0;
   for(int i=0;i<key.length();i++){
     hash+=(int)key.charAt(i);
   }
   hash=hash*599% hashTable.length;
  System.out.println(hash);
   return hash;
}
public HashNode get(String key){
  Integer index=hash(key);
  if(hashTable[index]!=null) {
    HashNode current = hashTable[index];
    while (current!=null){
     if(current.key==key){
       return current;
     }else {
       current=current.next;
     }
    }
  }
return null;
}
public boolean contains(String key){
Integer index=hash(key);
if(hashTable[index]!=null){
  HashNode current=hashTable[index];
  while (current!=null){
    if(current.key==key){
      return true;
    }else {
      current=current.next;
    }

  }
}
  return false;
}
}
