/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackandqueues;

public class App {

    public static void main(String[] args) {
 Stack test=new Stack();
 test.push(5);
 test.push(10);
 test.push(15);
 test.maxValue();
 System.out.println(test.maxValue());
    }

}
