/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stackandqueues;

public class App {

    public static void main(String[] args) {
 PseudoQueue test=new PseudoQueue();
      test.enqueue(20);
      test.enqueue(15);
      test.enqueue(10);
      test.enqueue(5);

    }

}
