/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Graph;

import org.junit.Test;

import java.util.HashSet;
import java.util.Set;

import static org.junit.Assert.*;

public class AppTest {
  @Test
  public void addNode() {
Graph test=new Graph();
    test.addNode(3);
    test.addNode(5);
    assertEquals("the result should be true ",true,test.getNodes().contains(3));
  }
  @Test
  public void addEdge() {
    Graph test = new Graph();
    Node a = test.addNode(3);
    Node b = test.addNode(5);
    assertTrue("should be true",test.addEdge(a,b));
  }

  @Test
  public void test_empty(){
    Graph test = new Graph();
    assertEquals(0,test.size());
    assertNull("It should be null ",test.getNodes());
  }
  @Test
  public void getNodes() {

    Graph test = new Graph();
    Node a = test.addNode(3);
    Node b = test.addNode(5);
    Node c = test.addNode(9);
    assertTrue("should be true ",test.getNodes().contains(a));
    assertTrue("should be true ",test.getNodes().contains(b));
    assertTrue("should be true ",test.getNodes().contains(c));
  }
  @Test
  public void test_onlyOne(){
    Graph test = new Graph();
    Node a = test.addNode(3);
    Set<Edge> expect = new HashSet<>();
    assertEquals("should be 1 ",1, test.size());
    assertEquals(expect,test.getNeighbors(a));
  }
}
